### ISSUE TITLE
i cant install forge

### ISSUE THREAD

**Issue by playstation452** [herbix/chunkLauncher#16]
everytime i try to install forge it says installation failed

**Comment by herbix** [comment]
@playstation452 what was the error message? A screenshot is prefered.

**Comment by playstation452** [comment]
![image](https://user-images.githubusercontent.com/98996547/236833674-93935ba8-4a6f-4a89-9bdb-e748669f412c.png)

**Comment by playstation452** [comment]
is there any way to fis that?

**Comment by herbix** [comment]
Can you please run it from commandline, install the game version and paste the outputs here?
```powershell
java -jar ChunkLauncher.jar
```
![image](https://user-images.githubusercontent.com/7110965/236853358-4e5ff199-666b-4c59-843b-8b895c3575aa.png)

The reason I'm asking was that I can install it correctly:
![image](https://user-images.githubusercontent.com/7110965/236853753-c22c9e3b-1234-46b4-bf2d-373ade3eb3e4.png)

**Comment by herbix** [comment]
Another steps you can try are:
1. Remove the forge folder `1.12.2-forge-14.23.5.2860` from `.minecraft\versions`.
2. Rerun forge installer again.
3. Open launcher and install remaining thing.

**Comment by playstation452** [comment]
thanks

**Comment by playstation452** [comment]
can you send like the forge folder becuase bothe of the methods dident work

**Comment by playstation452** [comment]
i got it to work tysm
