### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by artdeell** [herbix/chunkLauncher#2]
I created a russian translation for  this launcher. Can you push it to repo?
lang file is attached to this. (GitHub doesn't like .lang files so I put it into a ZIP)
[ru-RU.zip](https://github.com/herbix/chunkLauncher/files/4333230/ru-RU.zip)

**Comment by herbix** [comment]
Hi @artdeell. I can't download the zip file.
You can:
1. Fork this repo.
2. Update your repo by adding the translation.
3. Create a pull request with your commit.

This is the way github suggests.

**Comment by artdeell** [comment]
Now i created a pull request. The issue is closed.
