### ISSUE TITLE
How to get myself a clientid?

### ISSUE THREAD

**Issue by ghost** [herbix/chunkLauncher#5]
There is no document at all.

**Comment by herbix** [comment]
Please refer to: https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app
Client id is `Application (client) ID` here:
![image](https://user-images.githubusercontent.com/7110965/103134436-26ac8a00-46ec-11eb-9aaf-a1850d9a976b.png)

**Comment by ghost** [comment]
sloved.Thanks
